- name: "Install OSX version"
  homebrew:
    name: zsh
    state: latest
    update_homebrew: yes
  become: no
  when: ansible_os_family == "Darwin"
  
- name: "Install UBUNTU version"
  apt:
    name: zsh
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: "Set zsh as default shell"
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: yes

- name: "Install `antigen`"
  block:
    - name: "Install `antigen` - Checkout `antigen` to `~/.antigen`"
      git:
        repo: "https://github.com/zsh-users/antigen.git"
        dest: "{{ ansible_env.HOME }}/.antigen"
        force: yes
  when: not skip_antigen
